language: node_js
node_js:
    - '8.11.4'
before_install:
    - sudo apt-get install -y expect
before_script: curl https://cdn.wedeploy.com/cli/latest/wedeploy.sh -fsSL | bash
script: expect <(curl -s https://gist.githubusercontent.com/protoEvangelion/1b5bdea9343fe00460d9a3351a809d65/raw/9b81a820147d990f9bc3c58758cb7cd6b2354f62/we-ci.sh)
after_script: we deploy -p liferaydesign
