language: node_js
node_js:
  - '8.11.4'
cache:
  directories:
    - node_modules
before_script: ./deploy/deploy-common.sh
stages:
  - name: deploy-prod
    if: branch = master
  - name: deploy-dev
    if: branch = dev
jobs:
  include:
    - stage: deploy-prod
      script: ./deploy/deploy-prod.sh
    - stage: deploy-dev
      script: ./deploy/deploy-dev.sh

