---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
    - type: heading
      label: Markdown
    - type: directory
      path: src/markdown/articles
      label: Articles
      create: all
      match: '**/*'
      templates:
          - article
    - type: directory
      path: src/markdown/blueprints
      label: Blueprints
      create: all
      match: '**/*'
      new_doc_ext: md,.mdx
      templates:
          - handbook-article
    - type: directory
      path: src/markdown/careers
      label: Careers
      create: all
      match: '**/*'
      templates:
          - carreer
    - type: directory
      path: src/markdown/events
      label: Events
      create: all
      match: '**/*'
      templates:
          - events
    - type: directory
      path: src/markdown/handbook
      label: Handbook
      create: all
      match: '**/*'
      templates:
          - handbook-article
    - type: directory
      path: src/markdown/lexicon
      label: Lexicon (current)
      create: all
      match: '**/*'
      templates:
          - handbook-article
    - type: directory
      path: src/markdown/lexicon-1
      label: Lexicon (1.0)
      create: all
      match: '**/*'
      templates:
          - handbook-article
    - type: directory
      path: src/markdown/resources
      label: Resources
      create: all
      match: '**/*'
      templates:
          - handbook-article
    - type: directory
      path: src/markdown/team
      label: Team
      create: all
      match: '**/*'
      templates:
          - teammate
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
instant_preview: true
build:
    preview_command: gatsby build
    publish_command: gatsby build
    preview_output_directory: public
    output_directory: public
    instant_preview_command: gatsby develop -H 0.0.0.0 -p 7777 -o
    install_dependencies_command: npm install
    preview_docker_image: node:10
    mount_path: '/srv'
    working_dir: '/srv'
